### ISSUE TITLE
Add LaplaceRedux to MLJ's model registry

### ISSUE THREAD

**Issue by pasq-cat** [JuliaTrustworthyAI/LaplaceRedux.jl#115]
as title says. 
@pat-alt  you will  have to ask the admins at mlj to add the model?  or is there something i can do?

**Comment by pat-alt** [comment]
See [here](https://juliaai.github.io/MLJModelInterface.jl/dev/how_to_register/). Just need to ensure that we comply with guidelines and can the follow the linked docs for adding to the model registry

**Comment by pasq-cat** [comment]
@pat-alt  i will make a branch connected to this issue for the changes required to the interface.

**Comment by pasq-cat** [comment]
@pat-alt  i guess  we close this one,right?
