### ISSUE TITLE
Make plot and predict consistent 

### ISSUE THREAD

**Issue by pat-alt** [JuliaTrustworthyAI/LaplaceRedux.jl#116]
Should we return the observational noise when predicting from regression? 

- Currently, `predict` returns glm predictions for regression, not incorporating the observational noise (which I think I chose to do to stay consistent with PyTorch)
- In TaijaPlotting.jl, we plot the interval that contains both sources of noise (parameters and observational). 

In any case, we should add warnings and/or documentation

cc @pasq-cat

**Comment by pasq-cat** [comment]
![image](https://github.com/user-attachments/assets/5d182881-f981-40ee-8bb2-43694c7ef503)
 directly from alex immer github docs.

**Comment by pat-alt** [comment]
> ![image](https://private-user-images.githubusercontent.com/17205316/363486164-5d182881-f981-40ee-8bb2-43694c7ef503.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjQ0MjcsIm5iZiI6MTcyNTI2NDEyNywicGF0aCI6Ii8xNzIwNTMxNi8zNjM0ODYxNjQtNWQxODI4ODEtZjk4MS00MGVlLThiYjItNDM2OTRjN2VmNTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA4MDIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMjFmNjViMDg4MWExYzg4NDA3OTU2YzQzNmM0NzViZDI4ODFiNjgwNTJkMWQ2NTZjN2M5OGEwMTlhODQxMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OFA6YwudUGow9IaCfHb3ZdZffn79d2EF6LYQlRk_GmY) directly from alex immer github docs.

That's exactly the formula we use here for plotting. Let's discuss during our meeting.

**Comment by pat-alt** [comment]
addressed in #118
