### ISSUE TITLE
change  the verbose param of optimize_prior! from a boolean to an integer?

### ISSUE THREAD

**Issue by pasq-cat** [JuliaTrustworthyAI/LaplaceRedux.jl#125]
at the moment in the mlj interface the verbosity parameter accepted by mlj must be translated in a boolean through 
verbose = verbosity == 0 ? false : true

In accordance with MLJ, maybe we can change the verbose param in "verbosity" and change its nature to an integer so that in future different levels of informations can be displayed depending on the verbosity level set in MLJ.
Otherwise i will keep things as they are.

btw since the training loop of optimize_prior! is not exposed i cannot continue it in the MMI.update function, only start it from zero with a new number of steps.

**Comment by pasq-cat** [comment]
@pat-alt  before completing the interface there is also this.

**Comment by pat-alt** [comment]
Totally agree regarding verbosity. 

As for this

> btw since the training loop of optimize_prior! is not exposed i cannot continue it in the MMI.update function, only start it from zero with a new number of steps.

I'd have to think about it more. Worth having a separate issue for that?

**Comment by pasq-cat** [comment]
if , according to your experience, laplaceredux  only needs few hundred steps for the majority of cases then it's not really a problem and it's not worth the trouble.
If instead you think than for bigger problems the computational cost of starting from zero may be consistent then it may be a good idea to expose the training function. from what i have seen, it doesn't seem a problem.
