### ISSUE TITLE
Add a function to compute the average calibration in utils.jl

### ISSUE THREAD

**Issue by pasq-cat** [JuliaTrustworthyAI/LaplaceRedux.jl#90]
i would like to try to add a function that plot the average level of calibration in utils.jl.

the function is defined in https://arxiv.org/pdf/1807.00263

**Comment by Rockdeldiablo** [comment]
the end results should look like this for a miscalibrated network
![image](https://github.com/JuliaTrustworthyAI/LaplaceRedux.jl/assets/17205316/1566d780-f287-4187-adf0-38de219ed5c7)
and like this for a calibrated network
![image](https://github.com/JuliaTrustworthyAI/LaplaceRedux.jl/assets/17205316/ab3b8dcb-df99-4fb5-aa7a-2ea2ba707256)

**Comment by pat-alt** [comment]
Yes, nice idea! Have a look at https://github.com/devmotion/CalibrationErrors.jl for reference. It would be nice to have the basic evaluation function here, but the plotting in TaijaPlotting
